### PR TITLE
Bugfix/463 wrong png paths

### LINKED ISSUE #463: Assets and styles are being generated in the wrong folder.
## **Describe the bug**
All of the project's assets are being generated in the wrong folder when there is a specified name for the project(as depicted in the image). The styles and the assets are being generated in the `temp` folder, while the rest of the code is generated in the folder whose name was specified using the `-n` flag.

## **To Reproduce**
1. Switch to the `feat/responsive-ui` branch
2. Run PBC, specifying a name using the `-n` flag.
3. Generated project should look as in the image.

## **Impact of the problem**
Styles and assets are going to be missing, not to mention, the project is going to end up with two folders.

## **Environment:**
 - macos
 - `responsive-ui` branch

### PR DESCRIPTION
**Pull request by x64Eddie**
- Primarily, I fixed the issue with the pngs being generated in the incorrect place (if the name flag is used). Instead of the pngs being developed in a `temp` folder then moving to the correct one, the pngs are generated in the right assets folder from the start.  It's done by separating _flutter project creation_ and generating the dart files within the project; since we can determine if it will be a flutter project from the start, we can create the project and have the `png path` become the correct one.
- Secondly, and probably the most significant change, is the decoupling of the controller classes with the `main.dart` file. There were if statements that configured each of the controllers based on the type of design file. A controller is chosen from the list based on the corresponding design type, then configured, and finally, start ingesting the design file.
- Finally, added/removed attributes, getters, and functions to the `MainInfo()` Singleton for better access to information across the PBC's lifecycle.

### CODE REVIEW

File: lib/controllers/main_info.dart [hunk 1]
```diff
@@ -2,21 +2,56 @@ import 'dart:io';
...
 import 'package:sentry/sentry.dart';
+import 'package:path/path.dart' as p;
 
 class MainInfo {
   static final MainInfo _singleton = MainInfo._internal();
-  SentryClient sentry;
+  
+  final SentryClient _sentry = SentryClient(
+      dsn:
+          'https://6e011ce0d8cd4b7fb0ff284a23c5cb37@o433482.ingest.sentry.io/5388747');
```
Comment (SushiRoll53) [inline lib/controllers/main_info.dart:12]: Just making sure, there is no problem pushing this to the public

Comment (SushiRoll53) [reply lib/controllers/main_info.dart:12]: Nvm, I just remembered what it is, all good

File: lib/controllers/sketch_controller.dart [hunk 2]
```diff
@@ -82,7 +82,7 @@ class SketchController extends Controller {
 
       process = await Process.start('npm', ['run', 'prod'],
           workingDirectory:
-              p.join(MainInfo().cwd.path, '/SketchAssetConverter'));
+              p.join(MainInfo().cwd.path, 'SketchAssetConverter'));
```
Comment (x64Eddie) [inline lib/controllers/sketch_controller.dart:85]: Thank you @ivan-015 🙌🏼

**Review by SushiRoll53 — APPROVED** [review]
LGTM

**Review by ivan-015 — APPROVED** [review]
LGTM
